// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projebridgeapi.Models;

#nullable disable

namespace projebridgeapi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projebridgeapi.Models.Developers", b =>
                {
                    b.Property<int>("DevelopersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DevelopersId"));

                    b.Property<string>("DeveloperName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeveloperValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DevelopersId");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("projectbridgeapi.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Kolye",
                            Description = "Gold, silver ve taşlı kolye modelleri"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Yüzük",
                            Description = "Minimal, taşlı ve günlük yüzük modelleri"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Bileklik",
                            Description = "Çelik, rose ve zincir bileklik modelleri"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Küpe",
                            Description = "İnci, halka ve minimal küpe modelleri"
                        });
                });

            modelBuilder.Entity("projectbridgeapi.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "ayse@mail.com",
                            FullName = "Ayşe Yılmaz",
                            Phone = "0555 111 22 33"
                        },
                        new
                        {
                            CustomerId = 2,
                            Email = "elif@mail.com",
                            FullName = "Elif Demir",
                            Phone = "0555 222 33 44"
                        },
                        new
                        {
                            CustomerId = 3,
                            Email = "merve@mail.com",
                            FullName = "Merve Kaya",
                            Phone = "0555 333 44 55"
                        });
                });

            modelBuilder.Entity("projectbridgeapi.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            City = "İstanbul",
                            Phone = "0532 111 22 33",
                            SupplierName = "Parıltı Takı Tedarik"
                        },
                        new
                        {
                            SupplierId = 2,
                            City = "İzmir",
                            Phone = "0533 222 44 55",
                            SupplierName = "GoldLine Aksesuar"
                        },
                        new
                        {
                            SupplierId = 3,
                            City = "Ankara",
                            Phone = "0534 333 55 66",
                            SupplierName = "Rose Bijuteri"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
